version: "3.5"

services:
  nginx:
    image: nginx:1.17.8
    container_name: ${PROJECT_SHORTNAME}_nginx
    volumes:
      - ./webroot:/webroot
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - webnet
    ports:
      - "8080:80"

  php:
    build:
      context: docker/php
      dockerfile: Dockerfile
    container_name: ${PROJECT_SHORTNAME}_php
    volumes:
      - ./webroot:/webroot
    networks:
      - webnet
    environment:
      XDEBUG_CONFIG: "remote_host=${HOST_DEVICE} remote_enable=1"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

  mysql:
    image: mysql:8.0.17
    container_name: ${PROJECT_SHORTNAME}_mysql
    volumes: #TODO: mount volume for container database persistence
      - ./docker/mysql/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - webnet
    # mysql 8 normally uses default_authentication_plugin=caching_sha2_password
    # which is not yet compatible with the pdo_mysql php pdo driver
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:3306"

networks:
  webnet:
    driver: bridge #default